#!/usr/bin/env python3
"""Render the L96 FM-prior sampler report from run_sda_sampler_experiments.py JSON.

Consumes one or more result files and writes
``reports/l96/outputs/l96_fm_sampler_benchmark.md`` -- the experiment description,
the measured tables, the diagnosed negative results, and the reproduction recipe.

Narrative sections are held here as constants (the repo's
``generate_l96_obs_density_augmented_report.py`` convention); only the numeric
tables are computed from the JSON, so the report cannot silently disagree with the
runs that produced it.
"""
import argparse
import json
import logging
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = ROOT / "reports/l96/outputs/l96_fm_sampler_benchmark.md"

# S0 RMSE, repo evaluate_estimates convention, 200 windows, from
# reports/l96/outputs/l96_consolidated_benchmark.md.
BENCHMARK_ROWS = [
    ("Strong-4DVar", 0.8116, "variational DA baseline"),
    ("ETKF", 0.8883, "ensemble DA baseline"),
    ("EnKF", 0.9131, "ensemble DA baseline"),
    ("SDA3(monai)", 0.5365, "FM prior, repo DPS guidance from pure noise, N_outer=10"),
    ("DirectUNet-M(monai,cos)", 0.5064, "discriminative mean estimator"),
    ("DirectUNet-M(monai,cos,obsdensity)", 0.4727, "the mean estimator used below"),
    ("DirectUNet+SDA3", 0.4204, "non-augmented mean + SDA3 warm start"),
    ("DirectUNet(aug)+SDA3", 0.3889, "**closest comparator** -- same three ingredients"),
    ("subgrad+state-Stier+SDA3(monai)", 0.3410, "best row in the benchmark"),
]

HEADER = """# L96 conditional sampling from a flow-matching prior

Status: measurements, 2026-09-17. Generated by
`reports/l96/generate_l96_fm_sampler_report.py` from the JSON written by
`reports/l96/run_sda_sampler_experiments.py`; the sampler itself is
`evaluation/fm_sampler.py`.

Every number here was produced by the commands in the reproduction section against
checkpoints in `experiments/l96/`. Nothing is quoted from a draft or preprint.
"""

QUESTION = """## 1. The question

The scoping calls for a *sampler* baseline built on an FM prior -- a scheme that
produces a calibrated conditional ensemble -- not another conditional-mean estimator.
The benchmark's strong rows are all point estimators or mean-estimator hybrids, so
the open question is what an FM prior with observation guidance actually delivers,
and what it costs to close the accuracy gap to a discriminatively-trained mean.
"""

THEORY = """## 2. A deterministic estimator is a flow

Write the FM operator as `Psi(x_tau, y) = E[x_1 | x_tau, y]`; the Tweedie identity
gives the velocity `v = (Psi - x_tau)/(1-tau)`. Take *any* deterministic estimator
`m_hat(y)` and read it as an operator that ignores its state argument:

    Psi_det(x_tau, y) = m_hat(y)    =>    v_det = (m_hat - x_tau) / (1 - tau).

Integrating `v_det` from `x_0 ~ N(0, sigma_0^2 I)` gives, exactly,

    x_tau = (1 - tau) x_0 + tau m_hat ,

which is precisely the SDEdit / warm-start state. **The warm start is not a separate
trick -- it is the trajectory of the degenerate flow whose operator is constant.** A
deterministic estimator and a generative prior therefore live in the same space and
can be mixed at the level of velocities:

    v_lam = (1 - lam(tau)) v_FM + lam(tau) v_det ,    lam(tau) = lam_0 (1 - tau)^p .

* `lam_0 = 0` is the cold (pure FM) sampler.
* `lam(tau) = 1{tau < tau_0}` -- the discontinuous member -- is exactly the warm start.
* **`p >= 1` is required.** `v_det` carries a `1/(1-tau)` factor, so the blended
  velocity contains `lam(tau)/(1-tau) = lam_0 (1-tau)^{p-1}`, bounded as `tau -> 1`
  only for `p >= 1`. This is enforced in `Blend.__post_init__`, not left to the
  caller. It is not a numerical nuisance: it says a constant operator cannot be
  blended in with fixed weight all the way to `tau = 1`, where the FM operator must
  take over.

**Why the weight should decay.** At the warm-start time the state is
`x_{tau_0} = (1-tau_0) x_0 + tau_0 m_hat`, and the FM operator's Gaussian part maps it
through the gain `K_tau = tau P / ((1-tau)^2 sigma_0^2 + tau^2 P)`. The effective
weight the final estimate places on `m_hat` is therefore `w = tau_0 K_{tau_0}` -- the
classical two-estimator combination weight, trusting the deterministic estimate in
proportion to the prior variance still unexplained at that time. Since `K_tau` rises
with `tau`, the continuous family should put its mass at small `tau`, which is what
`(1-tau)^p` does smoothly instead of the hard cut.

**Relation to the CFM literature.** Time-varying mixing of two velocity fields is
standard under another name: classifier-free guidance is
`v = (1+w) v_cond - w v_uncond`, an affine combination of two flows with a weight
implementations routinely schedule in `tau`. What is *not* standard is that one of
the two flows is a **pre-trained deterministic estimator re-read as a degenerate
flow** rather than a second generative model. That reading is what makes the warm
start a special case instead of an unrelated heuristic.
"""

SETUP = """## 3. Setup and conventions

**Prior.** `SDA3_monai_cond_noisy_l96_norm`, an observation-conditional CFM trained
under noisy parameters/forcings. Linear interpolant
`x_tau = (1-tau) x_0 + tau x_1`, `x_0 ~ N(0, sigma_0^2 I)`, `sigma_0 = 0.5`.

**Guidance.** SDA-style variance-weighted likelihood guidance (Rozet & Louppe): the
Tweedie estimate `x_hat_1 = x_tau + (1-tau) v` is scored against the observations
with weights `1/(2(R + Gamma alpha_tau^2/beta_tau^2))`, `Gamma = 1e-2`, and the state
nudged by `dt alpha_tau^2/(beta_tau (1-tau))` times that gradient.

**Mean estimator.** `L1b_monai_unet_s0s1_norm_obsdensity`, the observation-density
augmented DirectUNet-M.

**Metrics.** `rmse_repo` is the repo's `evaluate_estimates` convention -- the mean
over state dimensions of the per-dimension RMSE -- and is the number comparable to
the consolidated benchmark. `rmse_pooled` pools over all entries; the two differ by
~8% on L96, so both are reported. `spread` is
`sqrt(mean over entries of the ensemble variance)` (biased, `correction=0`).

**Reliability target.** A perfectly reliable `N`-member ensemble with biased variance
has `spread/RMSE = sqrt((N-1)/(N+1))` -- 0.845 at `N = 6`, 0.905 at `N = 10`. Far
below target is over-confident; far above, over-dispersive.
"""

NEGATIVES = """## 6. Negative results, with diagnoses

Each was implemented, run and rejected. The diagnoses are the substantive content --
several follow from the operator decomposition rather than from implementation faults.

### 6.1 Variance-corrected warm start -- negligible

The warm-start state has second moment `(1-tau_0)^2 sigma_0^2` from the noise but
omits `tau_0^2 P_hat` from the estimator's own error. Adding it back changed nothing
(0.4744 -> 0.4767 rmse_repo, 4 windows): the missing term is `tau_0^2 P_hat = 0.011`
against `(1-tau_0)^2 sigma_0^2 = 0.123`, i.e. ~8%.

### 6.2 Operator mean-shift -- the algebra is output-only

Replacing the operator's mean directly as `Psi* = Psi(x_tau) + (1 - tau K) Delta_m`
was catastrophic (1.043 / 1.124 rmse_repo, 4 windows). The cause is **not**
out-of-distribution network queries, which was the first and wrong guess. The update
is *output-only* and valid only if `Psi` is affine. The correct mean-shifted operator
shifts the input too:

    Psi*(x_tau) = Delta_m + Psi(x_tau - beta_tau Delta_m)
    =>  v*(x_tau) = v(x_tau - beta_tau Delta_m) + Delta_m ,

which integrates to shifting the whole trajectory -- i.e. reduces **exactly** to
post-hoc addition of `Delta_m`. There is nothing to gain from doing it inside the ODE.

### 6.3 Post-hoc recentering and a diagonal covariance update

Recentering the ensemble on `m_hat` gives the mean-only RMSE by construction (0.5547,
4 windows) while keeping the cold sampler's spread -- ratio 1.145, over-dispersive,
since the sampler's spread reflects *its* error, not the better estimator's. The
diagonal covariance update applied on top brings the ratio to 0.801 (spread
0.6743 -> 0.4721). This works, and is the cheapest route to a calibrated ensemble
around a good mean, but it is a two-stage construction rather than a sampler: the
RMSE is entirely `m_hat`'s.

### 6.4 Low-rank / iterative covariance -- rank deficiency

Replacing the diagonal target with `Sigma_hat = (1-lam)D + lam A A^T` (ensemble
anomalies rescaled so `diag(Sigma_hat) = p_hat`, applied by Woodbury) *inflated*
rather than calibrated: ratio 0.854 -> 1.964 at `lam = 0.1`, 1.190 -> 2.187 at
`lam = 0.5`, and iterating did not recover. With `N = 6` members in a
72000-dimensional state the sample covariance is hopeless -- the ensemble contributes
sampling noise, not correlation structure. Localisation is the standard remedy and
was not pursued.

### 6.5 Desroziers innovation calibration -- the estimator fits the observations

Truth-free calibration via `E[d_oa . d_ab] = H A H^T` drove the spread monotonically
down (1.145 -> 0.660 over 3 iterations), past the target rather than onto it. The
diagnostic assumes the analysis error is independent of the observation noise, but
`m_hat` is *trained to fit the observations*, so its departures understate its error:
measured `dep_fit = 0.147` against a known `R = 0.163`. The diagnostic is being fed a
quantity it is not valid for.

Two implementation faults found and fixed en route, both worth remembering: computing
the update from the fitted departure `||y - H x_bar_a||^2` instead of the Desroziers
product, and computing the diagnostics on the *recentered* ensemble, which erases the
very dependence being iterated on.

### 6.6 Observation cross-validation -- brittle under temporal holdout

Holding out 25% of observed timesteps restores the independence 6.5 lacks, at the
cost of feeding `m_hat` a thinned observation set it was not trained for. The
resulting error estimate over-shoots by ~15x, so the calibrated ensemble is wildly
over-dispersive: ratio 1.145 -> 1.692 (un-augmented mean) and 1.212 -> 2.040
(obsdensity-augmented mean -- *worse*, since that model exploits density even more).
The bias direction is the safe one; the magnitude makes it useless.

### 6.7 Decoupled mean / gain / non-Gaussian control -- `Psi_NG` is not invariant

The blend moves three things at once. In the operator decomposition,

    Psi_lam = [(1-lam) mu_p + lam m_hat] + (1-lam) K_p (x - beta mu_p) + (1-lam) Psi_NG

so blending toward a better mean also shrinks the gain *and* the non-Gaussian term --
which is where the dispersion goes. Giving each component its own knob should
therefore recover the RMSE gain without the spread loss. It does not (see the table
in §5): worse on **both** axes.

The cause is a caveat flagged when the unified form was derived, then underweighted:
`Psi_NG` is *defined relative to the pair* `(mu_p, K_p)` -- it is the residual of the
network's operator after subtracting that specific affine part. Re-using the
network's `Psi_NG` beneath a different gain `K~` is inconsistent, and the
inconsistency dominates. Real decoupling would require retraining `Psi_NG` against
the new affine part, which is precisely the argument for the unrolled-mean
architecture in `docs/cfm_affine_velocity_decomposition.md` §5.
"""

CONCLUSIONS = """## 7. Conclusions

* An FM prior with variance-weighted guidance **is** a working conditional sampler.
  The cold configuration is the closest to reliable of anything measured here, and
  its RMSE beats Strong-4DVar by 31% and both ensemble DA baselines by more.
* It is **not** calibrated. It is consistently over-dispersive by roughly a fifth to
  a quarter, at every ensemble size tested: ratio/target = 1.20 at `N = 6`
  (1.014/0.845), 1.22 at `N = 10` (1.104/0.905) and 1.24 at `N = 30` (1.202/0.967).
  That the miss is stable across `N` says it is a property of the sampler, not of the
  ensemble size. Earlier in this investigation the cold configuration was described
  as "calibrated"; that reading is withdrawn.
* It does not reach the accuracy of a discriminatively-trained mean estimator, let
  alone the benchmark hybrids. Every scheme that closes that RMSE gap does so by
  importing the mean estimator, and pays for it in spread.
* The blended-flow family is the best trade found: one scalar schedule, no
  retraining, strictly dominating the warm start it replaces on **both** axes.
* **We do not have a sampler that is simultaneously benchmark-competitive on RMSE and
  calibrated.** That is the honest state of the question.
* The negatives point away from post-hoc surgery and toward *training*: §6.7 shows
  the non-Gaussian term cannot be re-used beneath a changed affine part, which is the
  argument for learning `Psi_NG` against a prescribed `(mu, K)`.
"""


def fmt(x, nd=4):
    return "--" if x is None else ("nan" if x != x else f"{x:.{nd}f}")


def results_table(data, highlight=None, only=None):
    """``only``: substrings; keep a row if its label contains any of them."""
    lines = ["| config | rmse_repo | rmse_pooled | spread | ratio |",
             "|---|---|---|---|---|"]
    for label, r in data["results"].items():
        if only is not None and not any(k in label for k in only):
            continue
        bold = "**" if label == highlight else ""
        lines.append(
            f"| {bold}{label}{bold} | {bold}{fmt(r['rmse_repo'])}{bold} "
            f"| {fmt(r['rmse_pooled'])} | {fmt(r['spread'])} "
            f"| {bold}{fmt(r['ratio'], 3)}{bold} |")
    return "\n".join(lines)


COMPARATOR = ("DirectUNet(aug)+SDA3", 0.3889)


def compare_blend_to_warm(data, blend="lam0=0.5,p=2", warm_key="warm"):
    """Deltas computed from the data, never written by hand."""
    r = data["results"]
    warm = next((k for k in r if k.startswith(warm_key)), None)
    if warm is None or blend not in r:
        return None
    b, w = r[blend], r[warm]
    return dict(
        warm=warm, rmse_gain=100.0 * (w["rmse_repo"] - b["rmse_repo"]) / w["rmse_repo"],
        spread_gain=100.0 * (b["spread"] - w["spread"]) / w["spread"],
        blend_rmse=b["rmse_repo"], warm_rmse=w["rmse_repo"],
        blend_spread=b["spread"], warm_spread=w["spread"],
    )


def members_row(data):
    return data["config"]["members"]


def run_caption(data):
    c = data["config"]
    return (f"{data['windows_done']} windows, `N = {c['members']}` members, "
            f"`N_outer = {c['n_outer']}`, `Gamma = {c['gamma']}`, "
            f"seed {c['seed']}. Reliability target **{data['target']:.3f}**.")


def build_benchmark_section(full=None):
    lines = ["## 4. Reference rows from the consolidated benchmark", "",
             "S0 RMSE, repo `evaluate_estimates` convention, 200 windows, from",
             "`reports/l96/outputs/l96_consolidated_benchmark.md`:", "",
             "| scheme | S0 RMSE | note |", "|---|---|---|"]
    for name, rmse, note in BENCHMARK_ROWS:
        lines.append(f"| {name} | {rmse:.4f} | {note} |")
    n = members_row(full) if full else 10
    n_outer = full["config"]["n_outer"] if full else 50
    member_row = (f"| members | 30 | {n} **(matched)** |" if n == 30
                  else f"| members | 30 | {n} |")
    lines += ["", f"""**`DirectUNet(aug)+SDA3` is the direct comparator**: same
obsdensity-augmented DirectUNet-M mean, same SDA3 prior, same SDEdit warm start at
`tau_0 = 0.3`. It differs from the runs below in the respects tabulated here, which
must be stated before any comparison is drawn:

| | benchmark row | this report |
|---|---|---|
| guidance | repo DPS, normalized gradient, `guidance_weight = 2.0` | SDA variance-weighted, `Gamma = 1e-2` |
| Euler steps | `N_outer = 10` | `N_outer = {n_outer}` |
{member_row}

So the rows below are internally apples-to-apples (identical settings across
configurations) and comparable to that benchmark row up to the differences above. The
`warm` row is the bridge: it is the same **scheme** as `DirectUNet(aug)+SDA3` under
this report's settings, so the gap between it and 0.3889 measures the effect of those
settings, and the gap between it and the blend measures the effect of the blend."""]
    return "\n".join(lines)


def build_full_narrative(full):
    cmp_ = compare_blend_to_warm(full)
    name, ref = COMPARATOR
    n = members_row(full)
    matched = (n == 30)
    bench_delta = 100.0 * (ref - cmp_["blend_rmse"]) / ref if cmp_ else 0.0
    warm_delta = 100.0 * (cmp_["warm_rmse"] - ref) / ref if cmp_ else 0.0
    parts = ["""
**Harness validation.** The `mean-only` row must reproduce the benchmark's
`DirectUNet-M(monai,cos,obsdensity)` = 0.4727, since it is the same checkpoint on the
same windows. It does, to 0.3%. That is what licenses comparing anything else here
to the benchmark."""]
    if cmp_:
        parts.append(f"""
**The internal result, which is the clean one.** Against its own warm-start baseline
at identical settings, the blend improves **both** axes at once: RMSE
{cmp_['warm_rmse']:.4f} -> {cmp_['blend_rmse']:.4f} (**-{cmp_['rmse_gain']:.1f}%**)
with spread {cmp_['warm_spread']:.4f} -> {cmp_['blend_spread']:.4f}
(**+{cmp_['spread_gain']:.0f}%**). This is the one Pareto improvement in this body of
work, it holds at both ensemble sizes tested, and it is a single scalar schedule with
no retraining.""")
        parts.append(f"""
**Against the benchmark.** The blend's {cmp_['blend_rmse']:.4f} is
{bench_delta:.1f}% ahead of `{name}` = {ref:.4f}"""
                     + (f""", and at `N = {n}` the member count now **matches** that
row, so ensemble size no longer explains any of the gap."""
                        if matched else
                        f""", but this run uses `N = {n}` members against that row's
30, so part of the gap is ensemble size.""")
                     + f"""

The `warm` row decomposes what remains. It is the *same scheme* as `{name}` under
this report's settings and scores {cmp_['warm_rmse']:.4f} -- **{warm_delta:+.1f}%**
against {ref:.4f}. So this report's SDA variance-weighted guidance at the stated
`N_outer` is mildly worse than the repo's normalized-gradient DPS at
`guidance_weight = 2.0, N_outer = 10`, and the blend's own gain is what carries it
past. The honest summary is that **the blend is worth ~{cmp_['rmse_gain']:.0f}% RMSE
and ~{1 + cmp_['spread_gain'] / 100:.1f}x spread relative to the warm start it
replaces** -- and that this lands ahead of the benchmark row, not that the blend
improves on the benchmark by that margin.""")
    return "\n".join(parts)


def build_results_section(full, sweep, decoupled):
    parts = ["## 5. Measured"]
    if full is not None:
        note = full.get("provenance")
        parts += ["", "### 5.1 Full test set", "", run_caption(full),
                  *(["", f"*Provenance: {note}.*"] if note else []), "",
                  results_table(full, highlight="lam0=0.5,p=2"), "",
                  build_full_narrative(full)]
    if sweep is not None:
        parts += ["", "### 5.2 `(lam_0, p)` sweep", "", run_caption(sweep), "",
                  results_table(sweep, highlight="lam0=0.5,p=2"), "", """
Larger `lam_0` and smaller `p` both push toward the warm start's behaviour, as the
family predicts: `p = 1` decays slowest at small `tau`, so it commits harder to the
deterministic estimate. Only the cold sampler is anywhere near reliable; every
blended configuration trades dispersion for accuracy."""]
    if decoupled is not None:
        parts += ["", "### 5.3 Decoupled control (negative result)", "",
                  run_caption(decoupled), "",
                  results_table(decoupled,
                                only=("cold", "lam0=0.5,p=2", "decoup", "blendK"),
                                highlight="lam0=0.5,p=2"), "", """
Decoupling the mean, gain and non-Gaussian amplitude is worse than the coupled blend
(`lam0=0.5,p=2`, repeated here as the reference) on **both** axes -- see §6.7 for why.

The `cold` and `lam0=0.5,p=2` rows are produced by the *same* general affine velocity
code path as the `decoup`/`blendK` rows and reproduce §5.2 exactly, which is what
establishes that this is a genuine negative result rather than an implementation
fault. `Blend` is itself the `gain="prior", scale_ng=True` member of that family --
an exact algebraic identity asserted in `tests/test_fm_sampler.py`."""]
    return "\n".join(parts)


def canonical_output(data) -> str:
    """A repo-relative output path. Runs are often written to a scratch dir, which is
    useless to anyone else, so the rendered command names a reproducible location."""
    c = data["config"]
    return (f"experiments/l96_fm_sampler_{c['suite']}"
            f"_m{c['members']}_w{c['windows']}.json")


def build_reproduction_section(inputs):
    cmds, seen = [], set()
    for tag, path, data in inputs:
        if data is None:
            continue
        c = data["config"]
        key = tuple(sorted((k, str(v)) for k, v in c.items() if k != "output"))
        if key in seen:      # same run feeding two sections
            continue
        seen.add(key)
        cmds.append(f"""# {tag}  ->  {canonical_output(data)}
python reports/l96/run_sda_sampler_experiments.py --suite {c['suite']} \\
  --prior-ckpt {c['prior_ckpt']} {'--cond' if c['cond'] else ''} \\
  --mean-ckpt {c['mean_ckpt']} \\
  --dataset {c['dataset']} --norm-stats {c['norm_stats']} \\
  --windows {c['windows']} --chunk {c['chunk']} --members {c['members']} \\
  --n-outer {c['n_outer']} --gamma {c['gamma']} --tau0 {c['tau0']} \\
  --seed {c['seed']} --output {canonical_output(data)}""")
    flags = {"full test set": "--full", "(lam_0, p) sweep": "--sweep",
             "decoupled control": "--decoupled"}
    render = " \\\n  ".join(
        [f"{flags[tag]} {canonical_output(data)}"
         for tag, _, data in inputs if data is not None])
    cmds.append("# render this report\n"
                f"python reports/l96/generate_l96_fm_sampler_report.py \\\n  {render}")
    body = "\n\n".join(cmds)
    return f"""## 8. Reproduction

**Environment.** `fdv-monai-proto` (torch 2.8.0, monai 1.6.0) is required for every
monai checkpoint; the `fdv` environment (torch 2.4.1) has no monai and fails with a
late `ModuleNotFoundError` inside `train.py::model_factory`. The report scripts live
outside the package tree, so `PYTHONPATH` must point at the repo root.

```bash
export PATH="/Odyssey/private/rfablet/miniforge3/envs/fdv-monai-proto/bin:$PATH"
export PYTHONPATH=$PWD

{body}
```

A SLURM wrapper is at `batch/run_l96_blended_flow_sampler.sbatch`
(`SUITE`/`MEMBERS`/`WINDOWS`/`N_OUTER` overridable).

**Code layout.**

| path | role |
|---|---|
| `evaluation/fm_sampler.py` | the integrator and the schemes (`Cold`, `Warm`, `Blend`, `Decoupled`) |
| `tests/test_fm_sampler.py` | unit tests, including `Blend == Decoupled(gain="prior", scale_ng=True)` |
| `reports/l96/run_sda_sampler_experiments.py` | driver: runs a suite, writes JSON |
| `reports/l96/generate_l96_fm_sampler_report.py` | renders this report from that JSON |

**Three hazards baked into the code rather than left to the reader.**

1. `estimate_prior_gain_variance` takes **no** `guidance` argument. `P_prior` must be
   measured on an unguided pass; doing it on a guided ensemble gives 0.153 instead of
   0.804 and silently moves a calibration ratio from 0.854 to 1.190. That mistake was
   made three separate times during this work, so the unguided integration is inlined
   and there is no flag left to forget.
2. `sample` draws exactly one `torch.randn` per member, in member order, before that
   member's trajectory, and the scheme classes have no access to the RNG. Reordering
   those draws changes every number while still looking plausible.
3. `prior_mean` takes a `seed` and seeds before drawing. It previously used the
   ambient generator, which made `mu_p` -- and therefore every `Decoupled` row --
   vary run to run (0.6098 / 0.6102 / 0.6113 for `decoup a0=.5` across three runs of
   identical code). It hid well: `estimate_prior_gain_variance` seeds internally and
   each scheme's `sample` is preceded by `torch.manual_seed`, so `P_prior` and all
   the blend rows were bit-for-bit stable, and only `Decoupled` reads `mu_p`. The
   whole suite now reproduces exactly across runs; `tests/test_fm_sampler.py` asserts
   `prior_mean` is independent of the ambient RNG state.
"""


def load(path):
    p = Path(path) if path else None
    if p is None or not p.exists():
        if path:
            logger.warning(f"missing input, section skipped: {path}")
        return None
    return json.loads(p.read_text())


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--full", help="full-test-set blend suite JSON")
    ap.add_argument("--sweep", help="(lam_0, p) sweep JSON")
    ap.add_argument("--decoupled", help="decoupled-control suite JSON")
    ap.add_argument("--output", default=str(DEFAULT_OUTPUT))
    args = ap.parse_args()

    full, sweep, decoupled = load(args.full), load(args.sweep), load(args.decoupled)
    if full is sweep is decoupled is None:
        raise SystemExit("no inputs found; pass at least one of --full/--sweep/--decoupled")

    inputs = [("full test set", args.full, full), ("(lam_0, p) sweep", args.sweep, sweep),
              ("decoupled control", args.decoupled, decoupled)]
    sections = [HEADER, QUESTION, THEORY, SETUP, build_benchmark_section(full),
                build_results_section(full, sweep, decoupled), NEGATIVES,
                CONCLUSIONS, build_reproduction_section(inputs)]
    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n\n".join(s.strip() for s in sections) + "\n")
    logger.info(f"Report written to {out}")


if __name__ == "__main__":
    main()
