"""Tables of the FM-operator score for the current L96 benchmark rows.

Reads the per-run JSONs of ``batch/run_l96_fm_score_current.sbatch`` and
``batch/run_l96_fm_score_da.sbatch`` and writes a markdown summary: per layout
and case, RMSE, pooled spread/skill, Gaussian FMS at each tau, the calibration
loss of the best scalar variance rescaling, and the non-Gaussian check (KDE vs
Gaussian at the KDE's variance). Learned rows: mean over seeds [min-max].

usage: python reports/l96/summarise_fm_score_current.py IN_DIR OUT_MD
"""
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

import numpy as np

ROWS = [
    ("ETKF", re.compile(r"^da_(reg|rand)_.*_(s[01])_ETKF_members$")),
    ("ETKS", re.compile(r"^da_(reg|rand)_.*_(s[01])_ETKS_members$")),
    ("VanillaCFM-M", re.compile(r"^vanillacfm_ep1200_seed\d_(reg|rand)_(s[01])$")),
    ("PredictStateCFM-M", re.compile(r"^predictstatecfm_ep1200_seed\d_(reg|rand)_(s[01])$")),
    ("SDA1-M", re.compile(r"^B4_sda1_monaiM_ep1200_l96_seed\d_(reg|rand)_(s[01])$")),
    ("SDA2-M", re.compile(r"^A3_sda2_monaiM_ep1200_l96_seed\d_(reg|rand)_(s[01])$")),
    ("SDA3-fix-M", re.compile(r"^A3_sda3fix_monaiM_ep1200_l96_seed\d_(reg|rand)_(s[01])$")),
    ("Hybrid DU-M→SDA3-fix-M", re.compile(r"^hybrid_DU1200s\d_sda3fix1200s1_(reg|rand)_(s[01])$")),
]
TAUS = ("0.0", "0.25", "0.5", "0.75")
LAYOUTS = {"reg": "regular 30-obs grid", "rand": "canonical random layouts"}


def metrics(d: dict) -> dict:
    g, sc = d["gauss"], d["scale"]["all"]
    out = {"rmse": d["rmse"], "ss": sc["pooled_spread_skill"]}
    for t in TAUS:
        out[f"fms{t}"] = g[t]["all"]
    for t in ("0.5", "0.75"):
        out[f"closs{t}"] = 100 * (sc[t]["c1"] - sc[t]["at_c_star"]) / sc[t]["c1"]
        out[f"cstar{t}"] = sc[t]["c_star"]
        out[f"ng{t}"] = 100 * (d["kde"][t]["all"] - sc[t]["kde_var"]) / sc[t]["kde_var"]
    return out


def collect(in_dir: Path) -> dict:
    runs = defaultdict(list)
    for f in sorted(in_dir.glob("*.json")):
        for name, rx in ROWS:
            m = rx.match(f.stem)
            if m:
                runs[(name, m.group(1), m.group(2))].append(metrics(json.loads(f.read_text())))
    return runs


def cell(vals: list[float], fmt: str) -> str:
    if len(vals) == 1:
        return format(vals[0], fmt)
    return f"{format(np.mean(vals), fmt)} [{format(min(vals), fmt)}–{format(max(vals), fmt)}]"


def main(in_dir: Path, out_md: Path) -> None:
    runs = collect(in_dir)
    L = ["# L96 P1 — FM-operator score, current benchmark rows", "",
         f"Generated by `reports/l96/summarise_fm_score_current.py` from `{in_dir}`.",
         "FMS in z-scored units², pooled over windows × time × 24 channels; learned rows: mean over seeds "
         "[min–max]. Calibration loss = share of FMS removed by the best scalar variance rescaling c* "
         "(grid 1/8–8); non-Gaussian = KDE FMS relative to the Gaussian at the KDE's variance (negative = "
         "shape helps).", ""]
    for lay, title in LAYOUTS.items():
        for case in ("s0", "s1"):
            L += [f"## {title}, {case.upper()}", "",
                  "| scheme | n | RMSE | spread/skill | FMS τ=0 | 0.25 | 0.5 | 0.75 | cal. loss 0.5 (c*) | "
                  "cal. loss 0.75 (c*) | non-Gauss 0.5 / 0.75 |",
                  "|---|---|---|---|---|---|---|---|---|---|---|"]
            for name, _ in ROWS:
                rs = runs.get((name, lay, case))
                if not rs:
                    continue
                col = {k: [r[k] for r in rs] for k in rs[0]}
                L.append(
                    f"| {name} | {len(rs)} | {cell(col['rmse'], '.3f')} | {cell(col['ss'], '.2f')} | "
                    + " | ".join(cell(col[f'fms{t}'], '.4f') for t in TAUS)
                    + f" | {np.mean(col['closs0.5']):.0f}% ({np.mean(col['cstar0.5']):.1f})"
                    f" | {np.mean(col['closs0.75']):.0f}% ({np.mean(col['cstar0.75']):.1f})"
                    f" | {np.mean(col['ng0.5']):+.1f}% / {np.mean(col['ng0.75']):+.1f}% |")
            L.append("")
    out_md.parent.mkdir(parents=True, exist_ok=True)
    out_md.write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main(Path(sys.argv[1]), Path(sys.argv[2]))
